package mongoTest.models

import mongoTest.models.types.{Book, Review}
import org.mongodb.scala.bson.codecs.Macros._
import org.mongodb.scala.MongoClient.DEFAULT_CODEC_REGISTRY
import org.bson.codecs.configuration.CodecRegistries.{fromProviders, fromRegistries}
import org.bson.codecs.configuration.CodecRegistry

/**
 * works only with scala 2 since it uses macros
 * but with mongo4cats the registry is generated by the library => can use scala 3
  */

//object BooksCodecRegistry {
//	val codecRegistry: CodecRegistry = fromRegistries(fromProviders(classOf[Book], classOf[Review]), DEFAULT_CODEC_REGISTRY)
//}
